[window]
title = "gfx-boxes"
width = 1920
height = 1080
virtual_width = 640
virtual_height = 360
fullscreen = true
vsync = true
scaling_quality = "linear"

[renderer]
background_color = [0, 0, 0]
object_color = [255, 255, 255]

[physics]
updates_per_second = 60

[debug]
enable_frame_capture = false
output_directory = "debug-output"
max_captured_frames = 5
frame_capture_interval = 100

[[objects]]
x = 100
y = 100
width = 50
height = 50
vx = 1
vy = 2

[[objects]]
x = 200
y = 200
width = 70
height = 70
vx = 2
vy = 1

[[objects]]
x = 300
y = 300
width = 60
height = 60
vx = -2
vy = -1

[[objects]]
x = 50
y = 50
width = 15
height = 15
vx = 3
vy = 1

[[objects]]
x = 500
y = 100
width = 25
height = 25
vx = -1
vy = 2

[[objects]]
x = 150
y = 250
width = 20
height = 20
vx = 2
vy = -1

[[objects]]
x = 400
y = 300
width = 30
height = 30
vx = -2
vy = -2

[[objects]]
x = 10
y = 350
width = 10
height = 10
vx = 1
vy = -3