[window]
width = 1920
height = 1080

[debug]
max_captured_frames = 10

[[objects]]
x = 100
y = 100
width = 100
height = 100
vx = 1
vy = 0

[[objects]]
x = 200
y = 200
width = 50
height = 50
vx = 2
vy = 1

[[objects]]
x = 300
y = 300
width = 75
height = 75
vx = -1
vy = -1
