[window]
title = "gfx-boxes"
width = 1920
height = 1080
virtual_width = 640
virtual_height = 360
#virtual_width = 3840
#virtual_height = 2160
fullscreen = true
vsync = true
scaling_quality = "linear"

[renderer]
background_color = [0, 0, 0]
object_color = [255, 255, 255]

[physics]
updates_per_second = 60
damping_factor = 1.0
max_speed = 5.0
min_speed = 0.0

[debug]
enable_frame_capture = false
output_directory = "debug-output"
max_captured_frames = 5
frame_capture_interval = 100

[[objects]]
x = 50
y = 50
width = 20
height = 20
vx = 1.2
vy = 1.6

[[objects]]
x = 550
y = 150
width = 40
height = 40
vx = -1.5
vy = 0.9

[[objects]]
x = 150
y = 300
width = 15
height = 15
vx = 0.5
vy = -1.5

[[objects]]
x = 50
y = 50
width = 8
height = 8
vx = 1.5
vy = 0.5

[[objects]]
x = 500
y = 100
width = 13
height = 13
vx = -0.8
vy = 1.6

[[objects]]
x = 150
y = 250
width = 10
height = 10
vx = 1.6
vy = -0.8

[[objects]]
x = 400
y = 300
width = 15
height = 15
vx = -1.0
vy = -1.0

[[objects]]
x = 10
y = 350
width = 5
height = 5
vx = 0.5
vy = -1.5

[[objects]]
x = 100
y = 10
width = 25
height = 25
vx = 1.0
vy = 1.8

[[objects]]
x = 300
y = 50
width = 10
height = 10
vx = -1.2
vy = 1.5

[[objects]]
x = 500
y = 20
width = 35
height = 35
vx = -0.8
vy = 1.0

[[objects]]
x = 20
y = 150
width = 18
height = 18
vx = 1.5
vy = -0.5

[[objects]]
x = 400
y = 180
width = 22
height = 22
vx = -1.0
vy = -1.0

[[objects]]
x = 100
y = 300
width = 30
height = 30
vx = 0.5
vy = -1.8

[[objects]]
x = 550
y = 320
width = 12
height = 12
vx = -1.8
vy = -0.5

[[objects]]
x = 320
y = 100
width = 8
height = 8
vx = 1.0
vy = -1.0